#! /usr/bin/env ruby
require 'rubygems'
require 'thin'
require 'active_resource'

module EOL
  module API

    class Dog < ActiveResource::Base;
    end

  end
end

# no, i don't use globals in real live ... this is a prototype!
$rails_app = Rack::Adapter::Rails.new :root => 'rails'
puts "Rails App OK?  #{ Rack::MockRequest.new($rails_app).get('/').status }"
